name: AWS ECR
author: Lee Sun-Hyoup <kciter@naver.com>
branding:
  icon: box
  color: orange
description: Logs into ECR and provides Docker credentials
inputs:
  account-id:
    description: AWS Account ID
    required: true
  repo:
    description: Name of your ECR repository
    required: true
  region:
    description: The AWS region
    required: true
  create-repo:
    description: Set this to true to create the repository if it does not already exist
    default: false
runs:
  using: docker
  image: Dockerfile