name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: build and push latest docker image to GCR
        run: |
          echo ${{ secrets.GCR_TOKEN }} | docker login ghcr.io -u kciter --password-stdin
          docker pull ghcr.io/kciter/aws-ecr-action:latest
          docker build . -t ghcr.io/kciter/aws-ecr-action:$GITHUB_SHA --cache-from ghcr.io/kciter/aws-ecr-action:latest
          docker push ghcr.io/kciter/aws-ecr-action:$GITHUB_SHA
