name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: docker login
        run: |
          echo ${{ secrets.GCR_TOKEN }} | docker login ghcr.io -u kciter --password-stdin

      - name: build and push latest docker image to GCR
        run: |
          docker build -t ghcr.io/kciter/aws-ecr-action:latest .
          docker push ghcr.io/kciter/aws-ecr-action:latest
